### PR TITLE
Remove deferred render

### PR DESCRIPTION
**Pull request by joeldrapper**
This change removes the deferred render pattern as something you can opt into and instead makes it the default behaviour, with one small difference. You can `yield` any content that was captured from the component. It is no longer vanished.

### CODE REVIEW

**Comment by hangsu** [comment]
Will this behavior be replaced with a `def deferred = true` as suggested in #784?

**Comment by joeldrapper** [comment]
> Will this behavior be replaced with a def deferred = true as suggested in https://github.com/phlex-ruby/phlex/issues/784?

This is actually a sketch I wanted to run by @willcosgrove for how we could merge deferred render and normal rendering so you don’t need to pick.

**Comment by stephannv** [comment]
@joeldrapper did this sketch failed? What are the plans about DeferredRender? I'm keeping an eye on this because my gem [Phlex::Slotable](https://github.com/stephannv/phlex-slotable) depends on DeferredRender.

**Comment by joeldrapper** [comment]
Yeah, I think we’re going to have to keep things essentially the way they’ve always been. I was hoping to be able to merge them together but there are too many issues. Phlex becomes less flexible.

**Pull request closed without merging**
